version: "3.8"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: form_builder
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    ports:
      - "8000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/form_builder
    depends_on:
      - db

volumes:
  db_data:
